// examples/todo/src/TodoList.tsx
import { useState, type FormEvent } from 'react'
import { Slot } from '@yatoi/slots'
import type { TodoStore } from './core/todos.js'
import { useTodos } from './contract/index.js'

export function TodoList({ todos }: { todos: TodoStore }) {
  const items = useTodos(todos)
  const [title, setTitle] = useState('')

  function handleSubmit(e: FormEvent) {
    e.preventDefault()
    todos.add(title)
    setTitle('')
  }

  return (
    <div className="todo-list">
      <form className="todo-add" onSubmit={handleSubmit}>
        <input
          type="text"
          placeholder="Add a todo…"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          aria-label="New todo title"
        />
        <button type="submit">Add</button>
      </form>

      {items.length === 0 && <p className="empty">No todos yet.</p>}

      <ul>
        {items.map((todo) => (
          <li key={todo.id} className={todo.done ? 'todo-row done' : 'todo-row'}>
            <input
              type="checkbox"
              checked={todo.done}
              onChange={() => todos.toggle(todo.id)}
              aria-label={`Mark "${todo.title}" ${todo.done ? 'not done' : 'done'}`}
            />
            <span className="todo-title">{todo.title}</span>
            {/* Contribution point: the calendar plugin drops a due-date
                field in here when installed, and nothing else about this
                component knows it exists. */}
            <Slot name="todo.item.extra" todo={todo} />
            <button type="button" className="todo-delete" onClick={() => todos.remove(todo.id)} aria-label={`Delete "${todo.title}"`}>
              ✕
            </button>
          </li>
        ))}
      </ul>
    </div>
  )
}

// examples/todo-vue/src/TodoList.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Slot } from '@yatoi/vue-slots'
import type { TodoStore } from './core/todos.js'
import { useTodos } from './contract/index.js'

const props = defineProps<{ todos: TodoStore }>()

const items = useTodos(props.todos)
const title = ref('')

function handleSubmit(): void {
  props.todos.add(title.value)
  title.value = ''
}
</script>

<template>
  <div class="todo-list">
    <form class="todo-add" @submit.prevent="handleSubmit">
      <input v-model="title" type="text" placeholder="Add a todo…" aria-label="New todo title" />
      <button type="submit">Add</button>
    </form>

    <p v-if="items.length === 0" class="empty">No todos yet.</p>

    <ul>
      <li v-for="todo in items" :key="todo.id" :class="todo.done ? 'todo-row done' : 'todo-row'">
        <input
          type="checkbox"
          :checked="todo.done"
          :aria-label="`Mark &quot;${todo.title}&quot; ${todo.done ? 'not done' : 'done'}`"
          @change="props.todos.toggle(todo.id)"
        />
        <span class="todo-title">{{ todo.title }}</span>
        <!-- Contribution point: the calendar plugin drops a due-date
             field in here when installed, and nothing else about this
             component knows it exists. `:todo="todo"` is a plain attr —
             TypeScript can't check this binding; see this example's
             README, "<Slot> props as attrs". -->
        <Slot name="todo.item.extra" :todo="todo" />
        <button
          type="button"
          class="todo-delete"
          :aria-label="`Delete &quot;${todo.title}&quot;`"
          @click="props.todos.remove(todo.id)"
        >
          ✕
        </button>
      </li>
    </ul>
  </div>
</template>
